# Generated by Django 3.2.19 on 2023-06-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersimage',
            options={'verbose_name': 'Фото пользователя', 'verbose_name_plural': 'Фото пользователей'},
        ),
        migrations.AlterField(
            model_name='usersimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
