# Generated by Django 3.2.19 on 2023-06-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
