# Generated by Django 3.2.19 on 2023-06-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20230608_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqfiles',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
